/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9-dev at Tue Jun 13 04:46:47 2017. */

#ifndef PB_ROBOT_DATA_PB_H_INCLUDED
#define PB_ROBOT_DATA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _RobotData_LedPattern {
    RobotData_LedPattern_OFF = 0,
    RobotData_LedPattern_COLORWIPE = 1,
    RobotData_LedPattern_RAINBOW = 2
} RobotData_LedPattern;
#define _RobotData_LedPattern_MIN RobotData_LedPattern_OFF
#define _RobotData_LedPattern_MAX RobotData_LedPattern_RAINBOW
#define _RobotData_LedPattern_ARRAYSIZE ((RobotData_LedPattern)(RobotData_LedPattern_RAINBOW+1))

/* Struct definitions */
typedef struct _RobotData {
    int32_t s0_pos;
    int32_t s1_pos;
    int64_t sonarf;
    int64_t sonarb;
    RobotData_LedPattern led_pattern;
/* @@protoc_insertion_point(struct:RobotData) */
} RobotData;

/* Default values for struct fields */
extern const int64_t RobotData_sonarf_default;
extern const int64_t RobotData_sonarb_default;
extern const RobotData_LedPattern RobotData_led_pattern_default;

/* Initializer values for message structs */
#define RobotData_init_default                   {0, 0, 0ll, 0ll, RobotData_LedPattern_OFF}
#define RobotData_init_zero                      {0, 0, 0, 0, (RobotData_LedPattern)0}

/* Field tags (for use in manual encoding/decoding) */
#define RobotData_s0_pos_tag                     1
#define RobotData_s1_pos_tag                     2
#define RobotData_sonarf_tag                     3
#define RobotData_sonarb_tag                     4
#define RobotData_led_pattern_tag                5

/* Struct field encoding specification for nanopb */
extern const pb_field_t RobotData_fields[6];

/* Maximum encoded size of messages (where known) */
#define RobotData_size                           46

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ROBOT_DATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
