/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Mon Jun  5 18:29:25 2017. */

#include "robot_data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const RobotData_LedPattern RobotData_led_pattern_default = RobotData_LedPattern_OFF;


const pb_field_t RobotData_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RobotData, s0_pos, s0_pos, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, RobotData, s1_pos, s0_pos, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, RobotData, sonar0, s1_pos, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, RobotData, sonar1, sonar0, 0),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, RobotData, led_pattern, sonar1, &RobotData_led_pattern_default),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
