/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Tue Jun 13 04:46:47 2017. */

#include "robot_data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const int64_t RobotData_sonarf_default = 0ll;
const int64_t RobotData_sonarb_default = 0ll;
const RobotData_LedPattern RobotData_led_pattern_default = RobotData_LedPattern_OFF;


const pb_field_t RobotData_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, RobotData, s0_pos, s0_pos, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, RobotData, s1_pos, s0_pos, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, RobotData, sonarf, s1_pos, &RobotData_sonarf_default),
    PB_FIELD(  4, INT64   , REQUIRED, STATIC  , OTHER, RobotData, sonarb, sonarf, &RobotData_sonarb_default),
    PB_FIELD(  5, UENUM   , REQUIRED, STATIC  , OTHER, RobotData, led_pattern, sonarb, &RobotData_led_pattern_default),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
